# Generated by Django 3.0.3 on 2020-03-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200319_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerlogin',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='password',
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='picture',
            field=models.ImageField(blank=True, upload_to='users/images'),
        ),
    ]
