# Generated by Django 3.0.3 on 2020-06-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customerlogin_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlogin',
            name='picture',
        ),
    ]
